#!/bin/bash

# usage: snappify-list repo

repo=$1
me=`basename "$0"`

if [ -z $repo ]; then
    echo usage: $me repo
    exit 1
fi

if [ ! -d "$repo" ]; then
    echo error: repository doesn\'t exist \"$repo\"
    exit 1
fi

if [ ! -d "$repo/meta" ]; then
    echo error: bad repository, \"$repo/meta\" doesn\'t exist
    exit 1
fi

for i in `ls -1c "$repo/meta"`; do
    echo `stat -c %y "$repo/meta/$i" | awk -F. '{print \$1}' | sed s/\ /./` \
         $i `cat "$repo/meta/$i"`
done
