#!/bin/bash

# usage: snappify-alias repo alias snap

me=`basename "$0"`
repo=$1
snapalias=$2
snap=$3

_usage() {
    echo "usage: $me repo [ alias [ snap ] ]"
}

if [ -z $repo ]; then
    _usage
    exit 1
fi

if [ ! -d "$repo" ]; then
    echo error: repository doesn\'t exist, \"$repo\"
    exit 1
fi

if [ ! -d "$repo/aliases" ]; then
    echo error: bad repository, \"$repo/aliases\" doesn\'t exist
    exit 1
fi

if [ ! -d "$repo/snaps" ]; then
    echo error: bad repository, \"$repo/snaps\" doesn\'t exist
    exit 1
fi

if [ -z $snapalias ]; then
    for i in `ls -1 "$repo/aliases"`; do
        echo $i '->' `cat "$repo/aliases/$i"`
    done
else
    if [ -z $snap ]; then
        if [ -f "$repo/aliases/$snapalias" ]; then
            cat "$repo/aliases/$snapalias"
        else
            aliaslen=${#snapalias}
            for i in `ls -1 "$repo/snaps"`; do
                if [ "${i:0:$aliaslen}" = "$snapalias" ]; then
                    echo $i
                fi
            done
        fi
    elif [ "$snap" = "-" ]; then
        if [ -f "$repo/aliases/$snapalias" ]; then
            rm "$repo/aliases/$snapalias"
            echo removed alias $snapalias
        fi
    else
        echo $snap > "$repo/aliases/$snapalias"
        echo $snapalias '->' $snap
    fi
fi
