#!/bin/bash
#
# snappify snapshot management suite
# github.com/mattferris/snappify
#
# Copyright (c) 2018 Matt Ferris
# Released under the BSD 2-clause license
# github.com/mattferris/snappify/blob/master/LICENSE.txt

# the location of the snap repo
root=".snappify"

# update the location of the snap repo if it was included in the environment
if [ ! -z "$SNAPPIFY_ROOT" ]; then
    root=$SNAPPIFY_ROOT
fi

# report an error
function err {
    echo "error: $2" >&2
    exit $1
}

# report a notice
function notice {
    echo "notice: $1" >&2
}

short=0

if [ ! -z "$1" -a -z "${1%%-*}" ]; then
    short=1
    shift
fi

# how many snapshots to display?
num=$1

# default to 5
if [ -z "$num" ]; then
    num=5
fi

# check if log file exists
if [ ! -f "$root/log" ]; then
    err 2 "no log contents yet"
fi

# display log
for hash in $(tail -n "$num" "$root/log"); do
    meta=$(snappify-read "$hash" | head -n1)
    message=$(snappify-read "$hash" | tail -n+2 | head -n1)
    user=$(echo $meta | cut -d\  -f1)
    date=$(echo $meta | cut -d\  -f2) 
    if [ $short = 0 ]; then
        echo "snapshot $hash"
        echo "Created by $user on $(date -d "@$date")"
        echo
        if [ ! -z "$message" ]; then
            echo "    $message"
            echo
        fi
    else
        echo "$(echo $hash | cut -b1-8) $message"
    fi
done
