#!/bin/bash
#
# snappify snapshot management suite
# github.com/mattferris/snappify
#
# Copyright (c) 2018 Matt Ferris
# Released under the BSD 2-clause license
# github.com/mattferris/snappify/blob/master/LICENSE.txt

# the location of the snap repo
root=".snappify"

# update the location of the snap repo if it was included in the environment
if [ ! -z "$SNAPPIFY_ROOT" ]; then
    root=$SNAPPIFY_ROOT
fi

# report an error
function err {
    echo "error: $2" >&2
    exit $1
}

# report a notice
function notice {
    echo "notice: $1" >&2
}

# collect arguments
alias=$1
hash=$2

if [ -z "$alias" ]; then
    if [ -d "$root/aliases" ]; then
        for i in $(ls -1 "$root/aliases"); do
            echo "$i -> $(cat "$root/aliases/$i")"
        done
    fi
elif [ -z "$hash" ]; then
    if [ -f "$root/aliases/$alias" ]; then
        cat "$root/aliases/$alias"
    elif [ $(echo -n "$alias" | wc -c) -ge 3 ]; then
        prefix=$(echo $alias | cut -b-2)
        suffix=$(echo $alias | cut -b3-)
        if [ -d "$root/objects/$prefix" ]; then
            num=$(ls -1 "$root/objects/$prefix/$suffix"* | wc -l)
            if [ $num = 1 ]; then
                path=$(ls -1 "$root/objects/$prefix/$suffix"*)
                fname=$(basename "$path")
                echo "$prefix$fname"
            fi
        fi
    else
        err 2 "alias undefined"
    fi
elif [ ! -z "$hash" ]; then
    if [ ! -d "$root/aliases" ]; then
        mkdir "$root/aliases" || err 2 "failed to create aliases directory"
    fi
    echo "$hash" > "$root/aliases/$alias"
else
    echo "usage: $(basename $0) [ <alias> [ <hash> ] ]" >&2
    exit 1
fi
