#!/bin/bash
#
# snappify snapshot management suite
# github.com/mattferris/snappify
#
# Copyright (c) 2018 Matt Ferris
# Released under the BSD 2-clause license
# github.com/mattferris/snappify/blob/master/LICENSE.txt

# the location of the snap repo
root=".snappify"

# update the location of the snap repo if it was included in the environment
if [ ! -z "$SNAPPIFY_ROOT" ]; then
    root=$SNAPPIFY_ROOT
fi

# report an error
function err {
    echo "error: $2" >&2
    exit $1
}

# report a notice
function notice {
    echo "notice: $1" >&2
}

# generate a checksum for a string
function strsum {
    echo -n "$1" | sha1sum | cut -d\  -f1
}

# generate a checksum for a file
function filesum {
    sha1sum $1 | cut -d\  -f1
}

# convert a relative path to an absolute one
function abspath {
    $(dirname "$root")/$1
}

# return the prefix of a hash
function prefix {
    echo -n "$1" | cut -b-2
}

# return the suffix of a hash
function suffix {
    echo -n "$1" | cut -b3-
}

# read metadata from the repo
function rmeta {
    hash=$1
    prefix=$(prefix "$hash")
    suffix=$(suffix "$hash")

    # check that metadata exists in repo
    if [ ! -f "$root/meta/$prefix/$suffix" ]; then
        err 2 "metadata doesn't exist"
    fi

    cat "$root/meta/$prefix/$suffix"
}

# read a file blob from the repo
function rblob {
    hash=$1
    prefix=$(prefix "$hash")
    suffix=$(suffix "$hash")

    # check that blob exists in repo
    if [ ! -f "$root/blobs/$prefix/$suffix" ]; then
        err 2 "blob doesn't exist"
    fi

    cat "$root/blobs/$prefix/$suffix"
}

# read snap metadata from the repo
function rsnap {
    hash=$1

    # check that snap exists in repo
    if [ ! -f "$root/snaps/$hash" ]; then
        err 2 "snapshot doesn't exist"
    fi

    cat "$root/snaps/$hash"
}

# determine relative path length
realbase=$(dirname $(realpath "$root"))
baselen=$(echo -n "$realbase/ " | wc -c)

# collect arguments
action=$1
hash=$2

# make sure we have everything we need
if [ -z "$hash" ]; then
    echo "usage: $(basename $0) { blob | meta | snap } <hash>"
    exit 1
fi

case $action in

    blob)
        rblob "$hash"
        ;;

    meta)
        rmeta "$hash"
        ;;

    snap)
        rsnap "$hash"
        ;;

    *)
        err 1 "unknown object type: $action"
        ;;

esac
